/**
 * Hook para integração com o SDK do Mercado Pago no checkout transparente.
 * Carrega o SDK JS e fornece a função de tokenização de cartão.
 */
import { useState, useEffect, useCallback } from 'react';
import { fetchSetting } from '@/lib/api';

declare global {
  interface Window {
    MercadoPago: any;
  }
}

let sdkLoaded = false;
let sdkPromise: Promise<void> | null = null;

function loadMercadoPagoSdk(): Promise<void> {
  if (sdkLoaded) return Promise.resolve();
  if (sdkPromise) return sdkPromise;

  sdkPromise = new Promise((resolve, reject) => {
    const script = document.createElement('script');
    script.src = 'https://sdk.mercadopago.com/js/v2';
    script.onload = () => { sdkLoaded = true; resolve(); };
    script.onerror = () => reject(new Error('Falha ao carregar SDK do Mercado Pago'));
    document.head.appendChild(script);
  });
  return sdkPromise;
}

export interface MpCardData {
  cardNumber: string;
  cardholderName: string;
  expirationMonth: string;
  expirationYear: string;
  securityCode: string;
  identificationType: string;
  identificationNumber: string;
}

export interface MpTokenizeResult {
  token: string;
  paymentMethodId: string;
  issuerId: string;
}

export interface UseMercadoPagoReturn {
  isReady: boolean;
  publicKey: string;
  tokenizeCard: (data: MpCardData) => Promise<MpTokenizeResult>;
  activeGateway: string;
  gatewayEnvironment: string;
  deviceSessionId: string;
}

export function useMercadoPago(): UseMercadoPagoReturn {
  const [isReady, setIsReady] = useState(false);
  const [publicKey, setPublicKey] = useState('');
  const [activeGateway, setActiveGateway] = useState('asaas');
  const [gatewayEnvironment, setGatewayEnvironment] = useState('sandbox');
  const [mpInstance, setMpInstance] = useState<any>(null);
  const [deviceSessionId, setDeviceSessionId] = useState('');

  useEffect(() => {
    let cancelled = false;

    const init = async () => {
      try {
        const [gateway, mpEnv, asaasEnv] = await Promise.all([
          fetchSetting('payment_gateway'),
          fetchSetting('mercadopago_environment'),
          fetchSetting('asaas_environment'),
        ]);

        if (cancelled) return;
        setActiveGateway(gateway || 'asaas');
        setGatewayEnvironment(
          gateway === 'mercadopago' ? (mpEnv || 'sandbox') : (asaasEnv || 'sandbox')
        );

        if (gateway !== 'mercadopago') return;

        const currentEnv = mpEnv || 'sandbox';

        // Try env-specific public key first, fallback to generic
        let mpPubKey = await fetchSetting(`mercadopago_public_key_${currentEnv}`);
        if (!mpPubKey) {
          mpPubKey = await fetchSetting('mercadopago_public_key');
        }

        if (cancelled || !mpPubKey) return;

        setPublicKey(mpPubKey);
        await loadMercadoPagoSdk();

        if (cancelled) return;

        const mp = new window.MercadoPago(mpPubKey, { locale: 'pt-BR' });
        setMpInstance(mp);
        setIsReady(true);

        // Capture Device Session ID for anti-fraud (generated by MP SDK automatically)
        const checkDeviceId = () => {
          const did = (window as any).MP_DEVICE_SESSION_ID;
          if (did) {
            setDeviceSessionId(did);
            console.log('[MP] Device Session ID captured:', did.substring(0, 12) + '...');
          }
        };
        // SDK may take a moment to generate it
        checkDeviceId();
        if (!(window as any).MP_DEVICE_SESSION_ID) {
          const interval = setInterval(() => {
            checkDeviceId();
            if ((window as any).MP_DEVICE_SESSION_ID) clearInterval(interval);
          }, 500);
          setTimeout(() => clearInterval(interval), 10000);
        }
      } catch (e) {
        console.error('Erro ao inicializar Mercado Pago:', e);
      }
    };

    init();
    return () => { cancelled = true; };
  }, []);

  const tokenizeCard = useCallback(async (data: MpCardData): Promise<MpTokenizeResult> => {
    if (!mpInstance) throw new Error('SDK do Mercado Pago não inicializado');

    const bin = data.cardNumber.replace(/\s/g, '').substring(0, 6);

    // Get payment method info from BIN
    let paymentMethodId = '';
    let issuerId = '';
    try {
      const pmResponse = await mpInstance.getPaymentMethods({ bin });
      if (pmResponse?.results?.length > 0) {
        paymentMethodId = pmResponse.results[0].id || '';
        issuerId = pmResponse.results[0].issuer?.id ? String(pmResponse.results[0].issuer.id) : '';
      }
    } catch (e) {
      console.warn('[MP] Could not detect payment method from BIN:', e);
    }

    // If no issuer from getPaymentMethods, try getIssuers
    if (paymentMethodId && !issuerId) {
      try {
        const issuers = await mpInstance.getIssuers({ paymentMethodId, bin });
        if (issuers?.length > 0) {
          issuerId = String(issuers[0].id);
        }
      } catch (e) {
        console.warn('[MP] Could not get issuers:', e);
      }
    }

    const cardTokenResponse = await mpInstance.createCardToken({
      cardNumber: data.cardNumber.replace(/\s/g, ''),
      cardholderName: data.cardholderName,
      cardExpirationMonth: data.expirationMonth,
      cardExpirationYear: data.expirationYear,
      securityCode: data.securityCode,
      identificationType: data.identificationType || 'CPF',
      identificationNumber: data.identificationNumber.replace(/\D/g, ''),
    });

    if (!cardTokenResponse?.id) {
      throw new Error('Falha na tokenização do cartão. Verifique os dados.');
    }

    console.log('[MP tokenizeCard] Result:', {
      token: cardTokenResponse.id.substring(0, 8) + '...',
      paymentMethodId,
      issuerId,
    });

    return {
      token: cardTokenResponse.id,
      paymentMethodId,
      issuerId,
    };
  }, [mpInstance]);

  return { isReady, publicKey, tokenizeCard, activeGateway, gatewayEnvironment, deviceSessionId };
}
